### ISSUE TITLE
Link do GD u nového writeru

### ISSUE THREAD

**Issue by padak** [keboola/gooddata-writer#12]
Pokud založím nový writer a v UI počkám až je v Jobech hotový (projekt existuje), dostanu při kliknutí na "enable access" error:
![image](https://cloud.githubusercontent.com/assets/1427901/12465871/b01163e0-bfd0-11e5-8309-2fc878333d36.png)

(gooddata-writer-c75387fe0fd6314578d91057849344ab)

Dovedu si představit, že to usera zmate. Možná to má snadné řešení, možná ne - jen to zkouším, no :)

Padák

**Comment by JakubMatejka** [comment]
Viz. https://github.com/keboola/kbc-ui/issues/468
