### ISSUE TITLE
Incremental load API bug

### ISSUE THREAD

**Issue by Halama** [keboola/gooddata-writer#16]
Z UI nastavuju inkrementální load na 2 dny:
![image](https://cloud.githubusercontent.com/assets/903531/13913457/3449b0f4-ef47-11e5-9ddb-dab1e4a1c694.png)

Po reloadu to ale vrací:
![image](https://cloud.githubusercontent.com/assets/903531/13913466/4d04fff4-ef47-11e5-9bd9-6d52b6e38b55.png)

Volá se API call http://docs.keboolagooddatawriterv2.apiary.io/#reference/project-model/tables/get-configured-table

`incrementalLoad` by co vím mělo vždy obsahovat číslo. `0` je full load, ostatní je `incremental`.
Tenhle bug se musel objevit nově protože to určitě fungovalo což je dost podezřelý.

**Comment by JakubMatejka** [comment]
Fixed by 54e452d468709d5e3fe76844a65b42a84e54ca79

Díky. Ach jo, procházelo to testama, protože `assertEquals(3, true);` je ok ;o( (https://github.com/keboola/gooddata-writer/blob/master/Tests/Unit/Configuration/DatasetsTest.php#L61). Nasadím to, jak to projde testama

**Comment by Halama** [comment]
@JakubMatejka nemělo by to v tom `incrementalLoad` vracet vždy číslo? S tím kdy se mění datový typ jedné property bývají dost problémy např. v JS nebo pokud by to někdo chtěl zpracovat json parserem nebo uložit do elasticu.

**Comment by Halama** [comment]
pak by zarroven v testech k tomu assertu na hodnotu slo pridat i `assertInternalType`
