### ISSUE TITLE
API - writerId

### ISSUE THREAD

**Issue by Halama** [keboola/gooddata-writer#2]
Ahoj,
mohl by writer akceptovat kromě `writerId` i `config` parametr? Sjednotilo by se to tím s ostatníma komponentama a nemuseli by se dělat pro writer výjimky v UI.
Super by bylo kdyby v moment kdy dostatne v parametru `writerId` k zakládanému jobu přidal i parametr `config` se stejnou hodnotou jako `writerId`. Pak by začlo fungovat linkování z jobu na writer apod. aniž by se muselo cokoliv měnit u uživatelů.

Takže např API call http://docs.keboolagooddatawriter.apiary.io/#post-%2Fgooddata-writer%2Fupload-project by vyžadoval zadat buď `writerId` nebo `config`, pokud by bylo zadáno oboje `config` by mělo asi prioritu.

**Comment by JakubMatejka** [comment]
Ahoj, mám to připravený, nebylo to ani nijak těžký. Writer pořád používá svůj writerId, jen k němu přidá config se stejnout hodnotou. Nebo načte writerId z configu pokud je prázdný. Pokud jsou tam oba tak přenastaví writerId na to co je v config (https://github.com/keboola/gooddata-writer/commit/7566a2cfac3f37d22fb36d648e85449fc83bb145). Je to tak ok? Přemýšlím jestli to může něco rozbít ;o)

**Comment by Halama** [comment]
Ahoj,
dívám se na ten commit a imho je to ok. Nenapadá mě čím by se to mohlo rozbít. Jedině že by tam někdo měl z nějakýho záhadnýho důvodu vedle writerId i ten parametr config. Netuším proč by to tam ale někdo měl, doteď tam ten parametr nic nedělal ne?

**Comment by JakubMatejka** [comment]
To mě napadlo že by tam někdo už ten parametr config měl. Ale maximálně omylem nebo z nějakých svých důvodů, žádný call Writeru ho určitě nepoužívá.

**Comment by Halama** [comment]
když by ten parametr config teď někdo použil uložilo by se to k tomu jobu? pokud jo tak by to šlo lehce ověřit.

**Comment by JakubMatejka** [comment]
To ne, není v indexu

**Comment by Halama** [comment]
jo zkoušel jsem to teď a není to tam. Tak nevím no, buď to nasadíme rovnou a budem předpokládat že si tam nikdo jen tak nepřidává parametr config. Nebo se nasadí verze kde se použití parametru config zaloguje a třeba po týdnu od nasazení se na to mrknem jestli ho někdo použil nebo ne.

**Comment by JakubMatejka** [comment]
No já už nic předpokládat raději nebudu. ;o) Dám tam nejdřív to logování.

**Comment by Halama** [comment]
Nebo vlastně pokud by si dal tu prioritu na writerId bude vše ok. Ničemu to podle mě vadit nebude protože nově tam např. orchestrátor nebo ui pak bude přidávat jenom config.

**Comment by Halama** [comment]
tzn. pokud bude zadáno oboje použije se writerId

**Comment by Halama** [comment]
díky, funguje to! :)
