### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by odinuv** [keboola/gooddata-writer#26]
Pokud použiju http://docs.keboolagooddatawriterv2.apiary.io/#reference/data-load/load-data-to-more-tables-at-once/load-data-to-more-tables-at-once a žádná z vyjmenovaných tabulek neexistuje nebo nemá povolený export tak to hodí 
ContextErrorException (0) in LoadDataMulti.php line 56: Warning: Invalid argument supplied for foreach()

https://papertrailapp.com/groups/170211/events?q=program%3Agooddata-writer&r=694559322398793745-694561521497559053

**Comment by JakubMatejka** [comment]
Fixed by 1b4316e
