### ISSUE TITLE
Incremental + load-data multi

### ISSUE THREAD

**Issue by odinuv** [keboola/gooddata-writer#27]
Tohle spravne nahraje data inkrementalne:
```curl -X POST -H "X-StorageAPI-Token: 578-..." -H "Content-Type: application/json" -d '{"incrementalLoad": 3,"tables": ["in.c-csv-import.test-62"]}' "https://syrup.keboola.com/gooddata-writer/v2/load_multi_test/projects/ot28xcqcszwkjzu87d5srqv0uvupjwq4/load"```

Tohle nahraje data full loadem:
```curl -X POST -H "X-StorageAPI-Token: 578-..." -H "Content-Type: application/json" -d '{"incrementalLoad": 3,"tables": ["in.c-csv-import.test-62"]}' "https://syrup.keboola.com/gooddata-writer/v2/load_multi_test/projects/ot28xcqcszwkjzu87d5srqv0uvupjwq4/load-multi"```

Jit by to melo http://docs.keboolagooddatawriterv2.apiary.io/#reference/data-load/load-data-to-more-tables-at-once/load-data-to-more-tables-at-once

**Comment by JakubMatejka** [comment]
Fixed by 1287fff. Díky
