### ISSUE TITLE
Create new configuration from old version

### ISSUE THREAD

**Issue by pivnicek** [keboola/gooddata-writer#34]
Most likely needs implementation.

**Comment by JakubMatejka** [comment]
I'm not sure I understand. Is it a bug? If it is an enhancement request, then it should go to Productboard first. ;o)

**Comment by pivnicek** [comment]
I suppose it's a bug, because the "create new configuration from old one" doesn't work, and the button is there in the UI.  But I imagine that it was maybe not have been considered as a possible thing for the gdwr. so here it is :-).  We'll figure something.
