### ISSUE TITLE
S3 client hardcoded connection url

### ISSUE THREAD

**Issue by Halama** [keboola/gooddata-writer#35]
https://github.com/keboola/gooddata-writer/blob/56dde32cf264aa6330dc1955279540dfabf39c2c/Service/Aws/S3Client.php#L101
Tady vidim ze je zahardcodovana URL connection tzn. nebude to spravne fungovat v jinem regionu.

Uplne nevim k cemu tahle trida slouzi ale vypada to jako uploader logu a ten uz v syrupu je spravne nastaveny. https://github.com/keboola/syrup/commit/18b55f7cf2e81dc6378fb76b5c6ccaa228f0abb2

https://github.com/keboola/syrup/releases/tag/5.0.0

Kdyby to slo tim nahradit tak by to bylo super.

**Comment by Halama** [comment]
koukam ze je pouzity na docela dost mistech, pak by mozna stacilo aby si z konfigurace vytahl tohle https://github.com/keboola/syrup/blob/18b55f7cf2e81dc6378fb76b5c6ccaa228f0abb2/app/config/parameters.yml.dist#L29

**Comment by Halama** [comment]
on dokonce pouziva ty parametry toho uploaderu, takze to je vlastne jednoduchy
https://github.com/keboola/gooddata-writer/blob/56dde32cf264aa6330dc1955279540dfabf39c2c/Resources/config/services.yml#L13

**Comment by JakubMatejka** [comment]
Fixed by 35d6618c7e1b0633261852c972fb5a8aac2ec2e4
