### ISSUE TITLE
multi region - update to syrup 4.0.7 or later

### ISSUE THREAD

**Issue by Halama** [keboola/gooddata-writer#37]
Aby šel gd-wr nainstalovat do jiného regionu je potřeba upgradnout na syrup 4.0.7 nebo ideálně na poslední verzi 5.x.x https://github.com/keboola/syrup/releases

**Comment by JakubMatejka** [comment]
Fixed by 35d6618c7e1b0633261852c972fb5a8aac2ec2e4
