### ISSUE TITLE
eu-central-1 issues

### ISSUE THREAD

**Issue by Halama** [keboola/gooddata-writer#38]
## Demo vs produkční token

[ ] Máme jenom jeden token, zaregistroval jsem ho jako demo i produkční. Tím se ale (zřejmě) děje to že při uploadu tabulky to dělá load dat dvakrát. Povolíme jenom produkční? Zažádáme o demo token?

*Update* - padak zazadal v GD o DEMO token

![image](https://cloud.githubusercontent.com/assets/903531/22059488/3f7d6dc0-dd6d-11e6-8196-ff00d5464e35.png)

Projekt je tam dvakrat:

![image](https://cloud.githubusercontent.com/assets/903531/22059527/7715ea14-dd6d-11e6-96fd-845957317577.png)

## Založení writeru z existujícího projektu

![image](https://cloud.githubusercontent.com/assets/903531/22065479/c3b25ab8-dd88-11e6-8e5b-46fabe2f14a2.png)

[x] Vyreseno bude fungovat stejne jako na soucasnem
- Dává tahle feature smysl když je default GD https://keboola.eu.gooddata.com/ kde bych neočekával že někdo bude mít existující projekt?
- Je možný tuhle feature kombinovat s Custom Domain?

**Comment by padak** [comment]
Ten token musíme řešit s "key accountem" - nestačí napsat na support. Teď jsem do toho zatáhl Milana (ani nevím, kdo ten náš account je) #fyi
