### ISSUE TITLE
PHP Undefined index: tasks

### ISSUE THREAD

**Issue by ErikZigo** [keboola/gooddata-writer#47]
Dneska skoncil jeden job interni chybou

`Undefined index: tasks` na

https://github.com/keboola/gooddata-writer/blob/de6cf21aeaf1fad5a656d9e2c4dfd0473d4370e2/Legacy/LegacyController.php#L1791

ID chyby `gooddata-writer-98b175989192be74a427189d85a49f4c`

koukam do PT a zatim tam vidim jen jednu tuhle chybu

**Comment by Halama** [comment]
Posledni tyden se to parkrat objevilo od jednoho writeru
https://connection.keboola.com/admin/utils/logs?file=2018/03/05/01/2018-03-05-01-09-40-5a9c8ac486668-exception
