### ISSUE TITLE
Modify PGP SSO authentication method

### ISSUE THREAD

**Issue by jiri-gd** [keboola/gooddata-writer#48]
For security reasons, the PGP SSO authentication method has been redesigned and the new version of the service passes the sensitive information via POST PGP login request instead of placing it into the GET request as it has been done in the past.

Please modify gooddata-writer by implementing new POST based PGP SSO authentication as described here:
[GoodData PGP Single Sign On](https://help.gooddata.com/display/developer/GoodData+PGP+Single+Sign-On)
and our API reference here:
[API reference - SSO PGP Login](https://help.gooddata.com/display/doc/API+Reference#/reference/authentication/sso-pgp-login)

Affected GoodData PGP SSO provider:
keboola.com
dev.keboola.com

We will temporarily keep the GET based PGP SSO authentication functional in parallel w/ the POST based PGP SSO authentication for our existing clients using the GET based PGP SSO authentication, but no new GET based PGP SSO authentication implementations are allowed anymore.

Any issues or feedback, please reach out to GD's support team.

Thanks!

Jiri @ GD

**Comment by JakubMatejka** [comment]
Hi @jiri-gd,
We are preparing a new version of the app which uses the POST login (see https://keboolagooddataprovisioning.docs.apiary.io/#reference/0/users/generate-claims-for-sso-access). The app's backend is ready and the frontend ui is in progress. Unfortunately, it will take some time to migrate all the users of the old app. (But to force them to migrate to a new version of this feature would take the same time so we decided not to fix it in this, almost deprecated, version.)

**Comment by jiri-gd** [comment]
Okay, do you have any estimate when is it going to be finished? We're expecting to disable the possibly insecure GET login during January 2018.

**Comment by JakubMatejka** [comment]
I'm afraid that our clients won't be that fast. ;o( Even if we update it in this old version, according to my experience it will take few months.

**Comment by jiri-gd** [comment]
Jakub, fresh news (looks like the information got delayed on our end). Deprecation of the GET method is due by June 2018 instead of previously January 2018. So this should provide sufficient amount of time to update old or build new client on your end and migrate customers. Let me know if this is still a concern or not.

Thanks,

Jiri

**Comment by jiri-gd** [comment]
@JakubMatejka any news on this issue? We're way past June 2018, so just want to ensure you guys are off the old method.

Thanks, Jiri @ GD

**Comment by JakubMatejka** [comment]
Oh, I'm sorry to let this unanswered but I believe it should be solved by now.
