### ISSUE TITLE
Custom date dimension

### ISSUE THREAD

**Issue by pivnicek** [keboola/gooddata-writer#49]
We need to adjust to the different way GD handles identifiers and labels for their new custom date dimensions: https://help.gooddata.com/display/doc/Custom+Calendars+-+Self+Service#CustomCalendars-SelfService-DateDimensionCSVFormat

> the correct identifier for data loading of this custom dimension is `{date_identifier}.date.day.us.mm_dd_yyyy` (but other dimensions we use have `{date_identifier}.date.mmddyyyy`)

**Comment by JakubMatejka** [comment]
I will probably manage it today, after all. So far it is fixed in gd php client: https://github.com/keboola/gooddata-php-client/releases/tag/2.6.4

**Comment by JakubMatejka** [comment]
So it is deployed. 🤞
