### ISSUE TITLE
Tracking changes?

### ISSUE THREAD

**Issue by odinuv** [keboola/gooddata-writer#5]
kacurez: workflow fail: atribut v gooddate je sedivy(predtym nebol), nevieme zistit kto urobil zmenu a co zmenil v modeli v gd writeru
(zistili sme to reverse enegineeringom)

https://keboola.slack.com/archives/tmp_datafestak/p1448714774000002

**Comment by JakubMatejka** [comment]
To šedivění je způsobený smazáním atributu na frontendu GD, to nejde přes nás a moc s tím nenaděláme. Sledování změn bude po přesunutí konfigurace ze sys stage do Configuration API. Prozatím zavírám.
