### ISSUE TITLE
Isolate KBC SSO access to specific KBC project

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/gooddata-writer#55]
Přidal bych sem id projektu: https://github.com/keboola/gooddata-writer/blob/be14fa2944245e2c5f1c4b5cff36f6046bcb831b/GoodData/ProjectAccess.php#L50 Na konkrétní konfigurace bych to neomezoval, to už by se docela komplikovalo.

A to by mělo být v zásadě všechno. Tabulku `kbc_projects_users` (která vlastně určuje, jestli se v ui objeví tlačítko `Enable`, nebo rovnou `GoodData Project`) to nijak neovlivní, ta obsahuje uid uživatele, který budou u nových userů nový.

**Comment by JakubMatejka** [comment]
Tak ne úplně, ještě je tam "cache" tabulka `kbc_users`, ze které se načítá uid uživatele pro danýho kbc usera, pokud existuje. Bude se muset rozšířit taky o id projektu.

**Comment by Halama** [comment]
jenom pro referenci předcházející diskuze https://keboola.slack.com/archives/C02CGRFK2/p1546533720014900
